### ISSUE TITLE
compose require 时报错，我用的是 laravel 6

### ISSUE THREAD

**Issue by patrick-zhao-51** [calchen/laravel-dingtalk-robot-notification#1]
compose require 时报错，我用的是 laravel 6，"require-dev":  中是 "phpunit/phpunit": "^8.0"，不知道该如何处理，谢谢！
 
----------------------------

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit (locked at 8.4.3, required as ^8.0) -> satisfiable by phpunit/phpunit[8.4.3].
    - calchen/laravel-dingtalk-robot-notification 1.2.0 requires phpunit/phpunit ^7.0 -> satisfiable by phpunit/phpunit[7.5.x-dev].
    - calchen/laravel-dingtalk-robot-notification 1.2.1 requires phpunit/phpunit ^7.0 -> satisfiable by phpunit/phpunit[7.5.x-dev].
    - calchen/laravel-dingtalk-robot-notification 1.2.2 requires phpunit/phpunit ^7.0 -> satisfiable by phpunit/phpunit[7.5.x-dev].
    - Conclusion: don't install phpunit/phpunit 7.5.x-dev
    - Installation request for calchen/laravel-dingtalk-robot-notification ^1.2 -> satisfiable by calchen/laravel-dingtalk-robot-notification[1.2.0, 1.2.1, 1.2.2].

**Comment by calchen** [comment]
抱歉现在才回复，已经升级到 6.0
